services:
  frontend:
    image: registry.gitlab.com/organisation/frontend-app:${CI_COMMIT_REF_SLUG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
